export const dashboards = [
  {
    id: "work",
    title: "My work",
    group: "Delivery",
    description:
      "A useful start to the day: tasks, reviews and blockers across tools.",
    sources: ["Cobalt tasks", "Connected issue trackers", "PRs"],
    uses: [
      "metric",
      "board",
      "activity",
      "filters",
      "detail",
      "freshness",
      "progress",
    ],
    visual: "board",
    outcome:
      "One personal queue without losing the original source or ownership.",
    features: [
      "Switch between grouped work and a compact list",
      "Open any task or issue in context",
      "Show source-specific actions only when supported",
    ],
    kind: "dashboard",
  },
  {
    id: "reviews",
    title: "Review inbox",
    group: "Delivery",
    description:
      "Make the next review obvious, with age, ownership and checks in view.",
    sources: ["GitHub / Azure DevOps", "Cobalt PRs"],
    uses: ["metric", "table", "activity", "filters", "detail", "freshness"],
    visual: "table",
    outcome:
      "Reduce waiting time by surfacing ready reviews and stale conversations.",
    features: [
      "Sort by waiting time or risk",
      "Filter assigned reviews, authors and repositories",
      "Inspect checks, discussions and the source PR",
    ],
    kind: "dashboard",
  },
  {
    id: "release",
    title: "Release readiness",
    group: "Delivery",
    description:
      "A single view of scope, checks, ownership and release blockers.",
    sources: ["Issues", "CI / CD via MCP", "PRs"],
    uses: [
      "metric",
      "timeline",
      "progress",
      "table",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "timeline",
    outcome: "Know what is blocking a release and who owns the next step.",
    features: [
      "Inspect milestone dependencies",
      "Open failing checks and unresolved scope",
      "Switch releases and compare readiness",
    ],
    kind: "dashboard",
  },
  {
    id: "service",
    title: "Service health",
    group: "Operations",
    description:
      "Latency, traffic and errors with the context needed to investigate.",
    sources: ["Datadog MCP", "Azure Monitor / analytics", "Any metrics MCP"],
    uses: [
      "metric",
      "series",
      "status",
      "breakdown",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "series",
    outcome:
      "See a change, isolate a service, and inspect the evidence behind it.",
    features: [
      "Compare services over a shared time window",
      "Overlay deploys and toggle metric series",
      "Drill into the slowest or least healthy service",
    ],
    kind: "dashboard",
  },
  {
    id: "incident",
    title: "Incident room",
    group: "Operations",
    description:
      "Correlate the current incident across metrics, logs and recent changes.",
    sources: ["Monitoring MCP", "Log / analytics MCP", "Deployments"],
    uses: [
      "metric",
      "series",
      "logs",
      "activity",
      "status",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "logs",
    outcome: "Give an on-call engineer a coherent investigation surface.",
    features: [
      "Filter all panels to one affected service",
      "Pause log display while collection continues",
      "Inspect event context and the release timeline",
    ],
    kind: "dashboard",
  },
  {
    id: "logs-view",
    title: "Log explorer",
    group: "Operations",
    description:
      "Search and inspect a bounded event stream without losing your place.",
    sources: ["Azure analytics", "Datadog logs", "Any log MCP"],
    uses: [
      "logs",
      "distribution",
      "breakdown",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "logs",
    outcome:
      "Find patterns, inspect raw events and understand missing history.",
    features: [
      "Search messages and filter severity",
      "Compare counts by service and time bucket",
      "Inspect a selected event with surrounding context",
    ],
    kind: "dashboard",
  },
  {
    id: "flow",
    title: "Delivery flow",
    group: "Delivery",
    description:
      "Understand aging work, throughput and the points where work gets stuck.",
    sources: ["Cobalt tasks", "Issue trackers", "PRs"],
    uses: [
      "metric",
      "board",
      "distribution",
      "heatmap",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "heatmap",
    outcome:
      "Improve delivery using work age and distribution, not vanity counts.",
    features: [
      "Explore work by team and workflow state",
      "Inspect aging items and cycle-time outliers",
      "Compare time periods with clear definitions",
    ],
    kind: "dashboard",
  },
  {
    id: "impact",
    title: "Release impact",
    group: "Operations",
    description:
      "Connect releases to changes in reliability and customer experience.",
    sources: ["CI / CD", "Metrics MCP", "Errors / issues"],
    uses: [
      "metric",
      "series",
      "activity",
      "table",
      "filters",
      "detail",
      "freshness",
      "status",
    ],
    visual: "series",
    outcome: "Compare before and after a deploy using the same source windows.",
    features: [
      "Select a deploy to align all time series",
      "Compare a baseline window and the release window",
      "Inspect new error groups and affected endpoints",
    ],
    kind: "dashboard",
  },
  {
    id: "cost",
    title: "Cloud cost & usage",
    group: "Business",
    description:
      "Understand spend, forecast pressure and the services driving change.",
    sources: ["Cloud billing MCP", "Usage / metrics MCP"],
    uses: [
      "metric",
      "series",
      "breakdown",
      "progress",
      "table",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "breakdown",
    outcome: "Explain a cost change and find where to investigate it.",
    features: [
      "Break down cost by service, team and environment",
      "Track a period budget with units and currency",
      "Inspect source line items and missing coverage",
    ],
    kind: "dashboard",
  },
  {
    id: "customers",
    title: "Customer health",
    group: "Business",
    description:
      "Combine adoption, support and account signals into an explainable view.",
    sources: ["CRM MCP", "Support MCP", "Product analytics"],
    uses: [
      "metric",
      "table",
      "heatmap",
      "activity",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "table",
    outcome:
      "Spot accounts needing attention without hiding the underlying evidence.",
    features: [
      "Inspect the inputs behind each health signal",
      "Filter segments, owners and changes",
      "Open source accounts, tickets and recent activity",
    ],
    kind: "dashboard",
  },
  {
    id: "analytics",
    title: "Product adoption",
    group: "Business",
    description:
      "Connect acquisition and activation to engagement and retention.",
    sources: ["Analytics MCP", "Warehouse MCP", "Product events"],
    uses: [
      "metric",
      "funnel",
      "heatmap",
      "series",
      "filters",
      "detail",
      "freshness",
    ],
    visual: "funnel",
    outcome: "See which step or cohort changed, with transparent denominators.",
    features: [
      "Compare segments through an activation funnel",
      "Inspect a retention cohort and its sample size",
      "Keep time windows and metric definitions visible",
    ],
    kind: "dashboard",
  },
  {
    id: "brief",
    title: "Workspace briefing",
    group: "Custom",
    description:
      "Compose an evidence-backed briefing from whichever sources the user chooses.",
    sources: [
      "Any authorized workspace source",
      "Connected MCP tools / resources",
    ],
    uses: [
      "narrative",
      "metric",
      "table",
      "breakdown",
      "activity",
      "filters",
      "freshness",
    ],
    visual: "narrative",
    outcome:
      "A source-agnostic example of reusable components composed into a useful report.",
    features: [
      "Combine narrative, metrics and selected records",
      "Show source references and partial-data notices",
      "Tailor the sections and data to the user’s question",
    ],
    kind: "dashboard",
  },
] as const;
export type DashboardKind = (typeof dashboards)[number]["id"];
